import { chromium } from 'file:///C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import { writeFile } from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const checks=[],errors=[];
const check=(name,pass)=>checks.push({name,pass:!!pass});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
await page.goto('http://localhost:4173');await page.evaluate(()=>document.fonts.ready);
await page.locator('.ribbon').scrollIntoViewIfNeeded();await page.waitForTimeout(400);
const start=await page.locator('.ribbon-track').evaluate(el=>getComputedStyle(el).transform);
await page.waitForTimeout(600);
check('ribbon moves right to left',await page.locator('.ribbon-track').evaluate((el,previous)=>new DOMMatrix(getComputedStyle(el).transform).m41<new DOMMatrix(previous).m41,start));
check('seamless infinite ribbon',await page.locator('.ribbon-track').evaluate(el=>getComputedStyle(el).animationIterationCount==='infinite'&&el.children[0].innerHTML===el.children[1].innerHTML));
await page.locator('.ribbon-toggle').click();check('ribbon pause control',await page.locator('.ribbon-track').evaluate(el=>getComputedStyle(el).animationPlayState==='paused'));
await page.locator('.ribbon-toggle').click();
await page.locator('.archive summary').click();check('first person archive',await page.locator('.archive summary').innerText()==='Más de mis videos');
check('nine actual linked covers',await page.locator('.archive-film').count()===9);
await page.evaluate(async()=>{for(const img of document.images)img.loading='eager';await Promise.all([...document.images].filter(i=>i.getAttribute('src')).map(i=>i.decode().catch(()=>{})));});
check('logo and covers load',await page.locator('.archive-frame img,.brilla-logo').evaluateAll(imgs=>imgs.every(i=>i.naturalWidth>0)));
await page.locator('#archive-next').click();await page.waitForTimeout(500);check('film strip navigation',await page.locator('#archive-links').evaluate(el=>el.scrollLeft>0));
await page.locator('#archive-previous').click();await page.waitForTimeout(500);await page.locator('.archive').screenshot({path:'qa/revision-archive.png'});
await page.locator('.service-list summary').first().hover();check('services open on hover',await page.locator('.service-list details').first().evaluate(e=>e.open));
await page.locator('.service-note').hover();await page.locator('.service-list summary').nth(1).focus();check('services open for keyboard focus',await page.locator('.service-list details').nth(1).evaluate(e=>e.open));
await page.locator('.brilla-gallery').scrollIntoViewIfNeeded();
check('gallery arrows and counter removed',await page.locator('.gallery-controls,#photo-count,#next-photo,#previous-photo').count()===0);
const before=await page.locator('.brilla-photo img').getAttribute('src');await page.waitForTimeout(5500);
check('photos advance automatically',before!==await page.locator('.brilla-photo img').getAttribute('src'));
await page.locator('.gallery-toggle').click();const paused=await page.locator('.brilla-photo img').getAttribute('src');await page.waitForTimeout(5000);
check('gallery pause works',paused===await page.locator('.brilla-photo img').getAttribute('src'));
await page.locator('.brilla').screenshot({path:'qa/revision-brilla.png'});
await page.goto('http://localhost:4173/?lang=en');check('English archive in first person',await page.locator('.archive summary').innerText()==='More of my videos');
check('compact desktop sections',await page.locator('.work').evaluate(el=>parseInt(getComputedStyle(el).paddingTop)<80));
for(const width of [360,390,768,935,1440]){
  await page.setViewportSize({width,height:844});await page.goto('http://localhost:4173');await page.evaluate(()=>document.fonts.ready);
  check(`no overflow at ${width}px`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
}
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://localhost:4173');await mobile.evaluate(()=>document.fonts.ready);
await mobile.locator('#service-list').scrollIntoViewIfNeeded();await mobile.waitForTimeout(250);
check('mobile first service opens before last',await mobile.locator('#service-list details').evaluateAll(rows=>rows[0].open&&!rows[3].open));
await mobile.waitForTimeout(2200);check('mobile sequence keeps all services open',await mobile.locator('#service-list details').evaluateAll(rows=>rows.every(r=>r.open)));
await mobile.locator('.services').screenshot({path:'qa/revision-mobile-services.png'});
await mobile.locator('.archive summary').click();await mobile.locator('.archive').screenshot({path:'qa/revision-mobile-archive.png'});
await mobile.emulateMedia({reducedMotion:'reduce'});await mobile.reload();await mobile.locator('.ribbon').scrollIntoViewIfNeeded();
check('reduced motion stops ribbon',await mobile.locator('.ribbon-track').evaluate(el=>getComputedStyle(el).animationName==='none'));
check('reduced motion exposes all mobile services',await mobile.locator('#service-list details').evaluateAll(rows=>rows.every(r=>r.open)));
check('no runtime or resource errors',errors.length===0);
await writeFile('qa/revision-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.filter(c=>c.pass).length,total:checks.length,failed:checks.filter(c=>!c.pass),errors}));
await browser.close();
